HotelsSample.Web/Models/SearchHit.cs
using System;
namespace FindSample.Models
{
    public class SearchHit
    {
        public string Title { get; set; }

        public Uri Url { get; set; }

        public string Location { get; set; }

        public string Text { get; set; }

        public int StarRating { get; set; }
    }
}

HotelsSample.Web/Controllers/BasicSearchController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using EPiServer.Find;
using EPiServer.Find.Helpers.Text;
using FindSample.Models;
using EPiServer.Sample.Hotels;

namespace FindSample.Controllers
{
    public class BasicSearchController : Controller
    {
        IClient client;

        public BasicSearchController()
        {
            this.client = HotelHelpers.HotelClient;
        }

        public ActionResult Index(string q)
        {
            if (q == null)
            {
                return View();
            }

            var results = client.Search<Hotel>()
                .For(q)
                .Select(x => new SearchHit
                            {
                                Title = x.Name,
                                Url = x.Website,
                                Location = new List<string> { x.ShortAddress, x.Location.Title, x.Location.Country.Title }.Concatenate(", "),
                                StarRating = (int) x.StarRating
                            })
                .GetResult();

            ViewBag.Query = q;
            ViewBag.Id = results.ProcessingInfo.ServerDuration;
            ViewBag.Hits = results.TotalMatching;

            return View(new SearchResult(results, q));
        }
    }
}

HotelsSample.Web/Controllers/FilteringController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using EPiServer.Find;
using EPiServer.Find.Helpers.Text;
using FindSample.Models;
using EPiServer.Sample.Hotels;

namespace FindSample.Controllers
{
    public class FilteringController : Controller
    {
        IClient client;

        public FilteringController()
        {
            this.client = HotelHelpers.HotelClient;
        }

        public ActionResult Index(string q, IEnumerable<string> chains, IEnumerable<string> countries)
        {
            //Retrieving values for fields that should be possible to filter on.
            //Often we would get these from a database, CMS or other source.
            var filterValues = client.Search<Hotel>()
                .Take(0)
                .TermsFacetFor(x => x.Chain, tfr => tfr.Size=50)
                .TermsFacetFor(x => x.Location.Country.Title, tfr => tfr.Size=50)
                .StaticallyCacheFor(TimeSpan.FromHours(1))
                .GetResult();

            ViewBag.Chains = filterValues.TermsFacetFor(x => x.Chain)
                .Select(x => new SelectListItem { Text = x.Term, Value = x.Term});

            ViewBag.Countries = filterValues.TermsFacetFor(x => x.Location.Country.Title)
                .Select(x => new SelectListItem { Text = x.Term, Value = x.Term});

            //As UrlHelper.Action doesn't add query string parameter with empty values
            //we need to check all parameters in case the user has searched without
            //entering a search term (he/she has just hit the search button)
            if (q == null && chains == null && countries == null)
            {
                return View();
            }

            ITypeSearch<Hotel> query = client.Search<Hotel>()
                .For(q);

            if (chains != null)
            {
                var chainFilter = client.BuildFilter<Hotel>();
                foreach (var chain in chains)
                {
                    chainFilter = chainFilter.Or(x => x.Chain.Match(chain));
                }
                query = query.Filter(chainFilter);
            }

            if (countries != null)
            {
                var countryFilter = client.BuildFilter<Hotel>();
                foreach (var country in countries)
                {
                    countryFilter = countryFilter.Or(x => x.Location.Country.Title.Match(country));
                }
                query = query.Filter(countryFilter);
            }

            var results = query.Select(x => new SearchHit
            {
                Title = x.Name,
                Url = x.Website,
                Location = new List<string> { x.ShortAddress, x.Location.Title, x.Location.Country.Title }.Concatenate(", "),
                StarRating = (int)x.StarRating
            })
                .GetResult();

            ViewBag.Query = q;
            ViewBag.Id = results.ProcessingInfo.ServerDuration;
            ViewBag.Hits = results.TotalMatching;

            return View(new SearchResult(results, q));
        }
    }
}

HotelsSample.Web/Views/Shared/Results.cshtml
@model HotelsSample.WebSandbox.Models.MainViewData
<div class="container">
    <b>Total Matching: </b>@Model.Results.TotalMatching &nbsp;
    <b>Server duration: </b>@Model.Results.ProcessingInfo.ServerDuration ms &nbsp;
    <b>Successful Shards: </b>@Model.Results.ProcessingInfo.Shards.Successful
    <div class="row">
        <div class="col-md-3">
            

            
            @if (Model.Results.Facets != null)
            {
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                    @for (int i = 0; i < Model.Results.Facets.Count(); i++)
                    {
                        var f = Model.Results.Facets.Skip(i).First();
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="@("Header"+i.ToString())">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#@("Collapse"+i.ToString())" aria-expanded="false" aria-controls="@("Collapse"+i.ToString())">
                                        @f.Name
                                    </a>
                                </h4>
                            </div>
                            <div id="@("Collapse"+i.ToString())" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="@("Header"+i.ToString())">
                                <div class="panel-body">
                                    @if (f is EPiServer.Find.Api.Facets.TermsFacet)
                                    {
                                        <ul class="list-group">
                                            @foreach (var k in (f as EPiServer.Find.Api.Facets.TermsFacet).Terms)
                                            {
                                                <li class="list-group-item" onclick="AddStringFilter('@f.Name','@k.Term')">
                                                    <span class="badge">@k.Count</span>
                                                    @k.Term
                                                </li>
                                            }
                                        </ul>
                                    }
                                    else if (f is EPiServer.Find.Api.Facets.HistogramFacet)
                                    {
                                        <ul class="list-group">
                                            @foreach (var k in (f as EPiServer.Find.Api.Facets.HistogramFacet).Entries)
                                            {
                                                <li class="list-group-item">
                                                    <span class="badge">@k.Count</span>
                                                    @k.Key
                                                </li>
                                            }
                                        </ul>
                                    }
                                </div>
                            </div>
                        </div>
                    }
                </div>
            }

        </div><div class="col-md-9">
            <ul class="list-group">
                @foreach (var h in Model.Results.Hits)
                {
                    <li class="list-group-item">
                        <h4 class="list-group-item-heading">@h.Document.Name</h4> @for (int i = 0; i < (int)h.Document.StarRating; i++)
                        { <span class="glyphicon glyphicon-star" aria-hidden="true"></span> }
                        <div class="row">
                            <div class="col-md-7">
                                <p class="list-group-item-text">
                                    @Html.Raw(h.Document.Description)
                                </p>
                            </div>
                            <div class="col-md-2">
                                    <dl class="dl-horizontal">
                                        <dt>Price USD</dt>
                                        <dd>@h.Document.PriceUSD</dd>
                                    </dl>
                                <dl class="dl-horizontal">
                                    <dt>Chain</dt>
                                    <dd>@h.Document.Chain</dd>
                                </dl>
                                <dl class="dl-horizontal">
                                    <dt>Country</dt>
                                    <dd>@h.Document.Location.Country.Title</dd>
                                </dl>
                                <dl class="dl-horizontal">
                                    <dt>Type</dt>
                                    <dd>@h.Document.PropertyType</dd>
                                </dl>
                                <dl class="dl-horizontal">
                                    <dt>Currency</dt>
                                    <dd>@h.Document.LocalCurrency</dd>
                                </dl>

                            </div>
                        </div>
                        <ul class="list-inline small well well-sm">
                            @if (h.Document.Features != null)
                            {
                                foreach (var f in h.Document.Features)
                                {
                                    <li><strong>@f</strong></li>
                                }
                            }
                        </ul>
                        <div class="row">
                            @for (int i = 0; i < h.Document.Images.Take(4).Count(); i++)
                            {
                                <div class="col-xs-6 col-md-3">
                                    <a href="#" class="thumbnail">
                                        <img src="http://hotelassets.episerverdemo.com/@h.Document.Images[i].Path">
                                    </a>
                                </div>
                            }

                        </div>
                    </li>
                }
            </ul>
        </div>
    </div>

</div>

HotelsSample.Web/Views/Shared/SearchHits.cshtml
@using FindSample.Models
@model SearchResult

<p>Found @Model.Results.TotalMatching restaurants matching "@Model.SearchTerm"</p>

<ol>
@foreach (SearchHit hit in Model.Results)
{
    <li>
        <h3>
            <a href="@hit.Url" data-ts="">@Html.Raw(hit.Title)</a>
            @for (int i = 0; i < hit.StarRating; i++)
            {
                <span class="michelin-star"></span>
            }
        </h3>
        <p>@hit.Location</p>
        @if (!string.IsNullOrWhiteSpace(hit.Text))
        {
            @Html.Raw(hit.Text)
        }
    </li>
}
</ol>

HotelsSample.Web/Views/Shared/_Layout.cshtml
@using SquishIt.Framework
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    @MvcHtmlString.Create(Bundle.Css()
        .Add("~/Content/bootstrap.min.css")
        .Add("~/Content/site.css")
        .Add("~/Content/themes/base/core.css")
        .Add("~/Content/themes/base/theme.css")
        .Add("~/Content/themes/base/autocomplete.css")
        .Add("~/Content/jquery.multiselect.css")
        .Render("~/combined_#.css"))

    @MvcHtmlString.Create(Bundle.JavaScript()
            .Add("~/Scripts/jquery-2.1.3.min.js")
            .Add("~/Scripts/jquery-ui-1.11.4.min.js")
            .Add("~/Scripts/jquery.multiselect.min.js")
            .Add("~/Scripts/truffler-stats.js")
            .ForceDebug()
            .Render("~/combined_#.js"))

</head>

<body>
    <nav class="navbar navbar-default navbar-static-top">
                <div class="container">
                    <div class="navbar-header"><h1>
    @Html.ActionLink("EPiServer Find Sample", "Index", "Home", null, new { @class = "brand" })
</h1>
                    </div>
                    <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Basic", "Index", "BasicSearch")</li>
                        <li>@Html.ActionLink("Sorting", "Index", "Sorting")</li>
                        <li>@Html.ActionLink("Paging", "Index", "Paging")</li>
                        <li>@Html.ActionLink("Highlighting", "Index", "Highlighting")</li>
                        <li>@Html.ActionLink("Filters", "Index", "Filtering")</li>
                        <li>@Html.ActionLink("Facets", "Index", "Facets")</li>
                        <li>@Html.ActionLink("Autocomplete", "Index", "Autocomplete")</li>
                        <li>@Html.ActionLink("Map", "Index", "Map")</li>
                    </ul>
                  </div>
                </div>
        </nav>
        <div class="container">
            <div class="content">
                @RenderBody()
            </div>
        </div>

        @if (System.Configuration.ConfigurationManager.AppSettings["statsCode"] != null)
        {
            var statsCode = System.Configuration.ConfigurationManager.AppSettings["statsCode"];
            <script src="//static.getclicky.com/js" type="text/javascript"></script>
            <script type="text/javascript">    try { clicky.init(@Html.Raw(statsCode)); } catch (e) { }</script>
            <noscript><p><img alt="Clicky" width="1" height="1" src="//in.getclicky.com/@Html.Raw(statsCode)ns.gif" /></p></noscript>
        }
</body>
</html>